[ERROR] 2018-07-09 09:52:12,556 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,569 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,581 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,599 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,611 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,632 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,650 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,663 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,684 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,702 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,717 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,731 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,750 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,768 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,785 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,801 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,816 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,833 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,858 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,874 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,903 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,920 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,934 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,950 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,963 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,979 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:12,995 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,013 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,028 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,044 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,062 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,079 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,102 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,117 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,131 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,149 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,167 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,182 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,197 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,211 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,241 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-09 09:52:13,263 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
