[ERROR] 2018-07-31 01:25:21,318 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,334 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,346 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,359 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,373 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,385 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,398 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,420 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,433 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,456 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,473 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,487 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,512 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,527 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,547 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,566 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,591 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,610 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,625 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,645 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,661 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,692 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,709 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,730 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,742 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 01:25:21,758 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 02:01:07,532 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-07-31 02:01:07.526435-10.0.2.2-771
[ERROR] 2018-07-31 04:54:55,093 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 04:55:01,525 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 04:55:05,373 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 04:55:05,775 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 04:55:06,132 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 06:20:21,933 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 13:04:47,513 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-07-31 13:04:47.470412-10.0.2.2-0c1
[ERROR] 2018-07-31 13:10:41,249 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-07-31 13:10:41.245171-10.0.2.2-ec6
[ERROR] 2018-07-31 13:10:48,226 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-07-31 13:10:48.223058-10.0.2.2-fb9
[ERROR] 2018-07-31 14:11:08,303 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 14:11:14,640 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 14:14:25,686 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:48:54,878 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:21,253 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:21,270 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:21,291 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:21,305 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:26,924 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:26,939 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:26,951 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
[ERROR] 2018-07-31 16:54:26,971 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: 'connection'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python2.7/inspect.py", line 888, in formatargvalues
    specs.append(strseq(args[i], convert, join))
  File "/usr/lib/python2.7/inspect.py", line 843, in strseq
    return convert(object)
  File "/usr/lib/python2.7/inspect.py", line 885, in convert
    return formatarg(name) + formatvalue(locals[name])
KeyError: 'connection'
